# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23538e754ba1c2ecb293fe26e466c29de443036ad8afb7ce30f7809fd2cf7d12b6670375768c40e62a6bebf735493133d96e33635a94635db854db8dd12725ed

test:
  secret_key_base: 5f5c67963b1706106fe80a8adeabb92594646e688281d1a530c27dc6337e36a6317408b6f74ee96853758b2e18b834cbb7a8f397b77e0a97747d2ed25c0b44be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
